spring.application.name=SeriesAnalyzer

# DB Login
spring.datasource.url=jdbc:mysql://localhost:3306/LoginDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# DB works
 series.datasource.url=jdbc:mysql://localhost:3306/SeriesDB?createDatabaseIfNotExist=true
 series.datasource.username=root
 series.datasource.password=mysql

 series.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 series.jpa.database-platform=org.hibernate.dialect.MySQLDialect
 series.jpa.hibernate.ddl-auto=update

server.port=8080

logging.level.root=INFO

# Niveles de logging especificos para tus paquetes
# logging.level.com.Login.Login.Controllers=DEBUG
# logging.level.com.Login.Login.Services=DEBUG
# logging.level.com.Login.Login.Repositories=INFO
# logging.level.com.Login.Login.Models=INFO

# Archivo de log
logging.file.name=application.log

#Key
jwt.secret.key="qwvebfvandakavdkadkmxftreitbcxftcibamnxziudiOZgyqzfqwfzofqwouqzvzfuqvdzqtcdfqytcfqicozakskvdiznfiqfdqiu"

